services:
  db:
    image: postgres:16
    container_name: foodflow-db
    environment:
      POSTGRES_DB: foodflow
      POSTGRES_USER: foodflow
      POSTGRES_PASSWORD: foodflow
    ports:
      - "5433:5432"
    volumes:
      - foodflow_pgdata:/var/lib/postgresql/data

volumes:
  foodflow_pgdata:
